# Combing data from multiple days / mice / conditions to create bigger data sets

In [11]:
import sys
sys.path.append('/Users/shayneufeld/GitHub/mouse_bandit/data_preprocessing_code')
sys.path.append('/Users/shayneufeld/GitHub/mouse_bandit')
import support_functions as sf
import numpy as np
import pandas as pd
import scipy as sp
import bandit_preprocessing as bp
from sklearn import preprocessing
import sys
import os
%matplotlib inline 

## load in csv files (from running exportTrials.m)

In [35]:
data = pd.read_csv('/Users/shayneufeld/GitHub/mouse_bandit/data/processed_data/new_master_8020_df.csv',index_col=0)

In [13]:
data.head(5)

Mouse ID  Session ID  Port Streak  Reward Streak  10_Port  10_Reward  \
0   dumble       70716         10.0           -1.0      1.0        1.0   
1   dumble       70716         10.0           -2.0      1.0        1.0   
2   dumble       70716          1.0           -3.0      1.0        1.0   
3   dumble       70716          2.0           -4.0      1.0        1.0   
4   dumble       70716          1.0            1.0      1.0        1.0   

   10_ITI  10_trialDuration  9_Port  9_Reward   ...    2_Reward  2_ITI  \
0   1.801             0.439     1.0       1.0   ...         1.0  2.234   
1   1.828             0.353     1.0       1.0   ...         0.0  2.133   
2   1.917             0.416     1.0       1.0   ...         0.0  1.411   
3   2.160             0.661     1.0       1.0   ...         0.0  2.169   
4   2.411             0.348     1.0       0.0   ...         0.0  3.838   

   2_trialDuration  1_Port  1_Reward  1_ITI  1_trialDuration  0_ITI  Decision  \
0            0.325     1.0       0.0  2.133            0.482  1.411       1.0   
1            0.482     1.0       0.0  1.411            0.435  2.169       0.0   
2            0.435     0.0       0.0  2.169            0.395  3.838       0.0   
3            0.395     0.0       0.0  3.838            0.469  1.846       1.0   
4            0.469     1.0       1.0  1.846            0.378  1.527       1.0   

   Switch  
0     0.0  
1     1.0  
2     0.0  
3     1.0  
4     0.0  

[5 rows x 47 columns]

In [51]:
data['Session ID'][0]

0    70716
0    70816
0    71116
0    71216
0    71316
0    71416
0    71516
0    72216
0    72516
0    72616
0    70716
0    70816
0    71116
0    71216
0    71316
0    71416
0    71516
0    72216
0    72516
0    72616
Name: Session ID, dtype: int64

## Do one-hot encoding for mouse ID and session ID

In [14]:
def encode_categorical(array):
    if not (array.dtype == np.dtype('float64') or array.dtype == np.dtype('int64')) :
        return preprocessing.LabelEncoder().fit_transform(array) 
    else:
        return array

In [15]:
categorical = (data.dtypes.values != np.dtype('float64'))
data_1hot = data.apply(encode_categorical)

In [16]:
# Apply one hot endcoing
encoder = preprocessing.OneHotEncoder(categorical_features=categorical, sparse=False)  # Last value in mask is y
x = encoder.fit_transform(data_1hot.values)

In [52]:
encoder.feature_indices_

array([    0,     2, 72619])

In [53]:
encoder.active_features_

array([    0,     1, 70718, 70818, 71118, 71218, 71318, 71418, 71518,
       72218, 72518, 72618])

In [22]:
np.unique(data['Session ID'].values)

array([70716, 70816, 71116, 71216, 71316, 71416, 71516, 72216, 72516, 72616])

In [21]:
x.shape

(11326, 57)

## Try function

In [3]:
data_encoded = bp.OneHotEncode(data)

In [9]:
master_matrix.to_csv(os.path.join(root_dir,'new_master_8020_df.csv'))

In [10]:
master_matrix

Mouse ID Session ID  Port Streak  Reward Streak  10_Port  10_Reward  \
0     dumble     070716         10.0           -1.0      1.0        1.0   
1     dumble     070716         10.0           -2.0      1.0        1.0   
2     dumble     070716          1.0           -3.0      1.0        1.0   
3     dumble     070716          2.0           -4.0      1.0        1.0   
4     dumble     070716          1.0            1.0      1.0        1.0   
5     dumble     070716          2.0           -1.0      1.0        0.0   
6     dumble     070716          3.0            1.0      1.0        1.0   
7     dumble     070716          4.0            2.0      1.0        1.0   
8     dumble     070716          5.0            3.0      1.0        1.0   
9     dumble     070716          6.0            4.0      1.0        0.0   
10    dumble     070716          7.0            5.0      1.0        0.0   
11    dumble     070716          8.0            6.0      0.0        0.0   
12    dumble     070716          9.0            7.0      0.0        0.0   
13    dumble     070716         10.0            8.0      1.0        1.0   
14    dumble     070716         10.0           -1.0      1.0        0.0   
15    dumble     070716         10.0            1.0      1.0        1.0   
16    dumble     070716         10.0            2.0      1.0        1.0   
17    dumble     070716         10.0            3.0      1.0        1.0   
18    dumble     070716         10.0            4.0      1.0        1.0   
19    dumble     070716         10.0            5.0      1.0        1.0   
20    dumble     070716         10.0            6.0      1.0        1.0   
21    dumble     070716         10.0            7.0      1.0        1.0   
22    dumble     070716         10.0            8.0      1.0        1.0   
23    dumble     070716         10.0            9.0      1.0        0.0   
24    dumble     070716         10.0            0.0      1.0        1.0   
25    dumble     070716         10.0            0.0      1.0        1.0   
26    dumble     070716         10.0           -1.0      1.0        1.0   
27    dumble     070716         10.0            1.0      1.0        1.0   
28    dumble     070716         10.0            2.0      1.0        1.0   
29    dumble     070716         10.0            3.0      1.0        1.0   
..       ...        ...          ...            ...      ...        ...   
529    harry     072616         10.0           -1.0      1.0        1.0   
530    harry     072616         10.0            1.0      1.0        0.0   
531    harry     072616         10.0            2.0      1.0        1.0   
532    harry     072616         10.0            3.0      1.0        1.0   
533    harry     072616         10.0           -1.0      1.0        0.0   
534    harry     072616         10.0            1.0      1.0        1.0   
535    harry     072616         10.0           -1.0      1.0        1.0   
536    harry     072616         10.0           -2.0      1.0        1.0   
537    harry     072616         10.0            1.0      1.0        1.0   
538    harry     072616         10.0           -1.0      1.0        0.0   
539    harry     072616         10.0           -2.0      1.0        1.0   
540    harry     072616         10.0            1.0      1.0        1.0   
541    harry     072616         10.0           -1.0      1.0        1.0   
542    harry     072616         10.0           -2.0      1.0        0.0   
543    harry     072616         10.0           -3.0      1.0        1.0   
544    harry     072616         10.0           -4.0      1.0        0.0   
545    harry     072616         10.0           -5.0      1.0        0.0   
546    harry     072616         10.0           -6.0      1.0        1.0   
547    harry     072616         10.0            1.0      1.0        0.0   
548    harry     072616         10.0           -1.0      1.0        0.0   
549    harry     072616         10.0           -2.0      1.0        1.0   
550    harry     072616      